parameters:
  sources:
    type: !php/const App\Services\DataProviders\Factories\ProviderFactory::YAML_TYPE
    sources:
      - name: !php/const App\Lib\Sources::MDS_VOICE
        informer:
          type: !php/const App\Lib\DataProviderTypes::JSON_TYPE
          url: 'http://ice.planeset.ru:8000/status-json.xsl'
          login: 'login1'
          password: 'pass1'

      - name: !php/const App\Lib\Sources::MDS_MUSIC
        informer:
          type: !php/const App\Lib\DataProviderTypes::MPD_TYPE
          url: 'url2'
          login: 'login2'
          password: 'pass2'
  json_mapping:
    !php/const App\Lib\Sources::MDS_VOICE: 'http://ice.planeset.ru:8000/mds_voice.mp3'
    !php/const App\Lib\Sources::MDS_MUSIC: 'http://ice.planeset.ru:8000/mds.mp3'